[package]
name = "fluvio-wasm-filter-odd"
version = "0.0.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
edition = "2021"
publish = false

[lib]
crate-type = ['cdylib']

[dependencies]
thiserror = { workspace = true }
fluvio-smartmodule = { workspace = true }
