[package]
name = "fluvio-smartmodule-aggregate-with-timestamp"
version = "0.0.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
edition = "2021"
publish = false

[lib]
crate-type = ['cdylib']

[dependencies]
chrono = { workspace = true }

# Fluvio
fluvio-smartmodule = { workspace = true }
