[package]
name = "fluvio-wasm-map-regex"
version = "0.0.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
edition = "2021"
publish = false

[lib]
crate-type = ['cdylib']

[dependencies]
regex = { workspace = true }
once_cell = { workspace = true }
fluvio-smartmodule = { workspace = true }